# Generated by Django 3.2.5 on 2022-10-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('create_time', models.TimeField(auto_now_add=True, verbose_name='采集时间')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='采集日期时间')),
                ('percent_avg', models.FloatField(verbose_name='cpu平均使用率')),
                ('percent_per', models.CharField(max_length=200, verbose_name='每核cpu使用率')),
                ('num_p', models.IntegerField(verbose_name='核心数量')),
                ('num_l', models.IntegerField(verbose_name='线程数量')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
